### ISSUE TITLE
Feature Request: Filters

### ISSUE THREAD

**Issue by b1twise** [teststaybaka/danmage#1]
YT streams often have translators who prepend [EN] etc to their translations. It would be very helpful to me if I could only display those message with something like a custom regexp. Hopefully this request would be considered.

**Comment by teststaybaka** [comment]
so you are saying, instead of regexp that blocks chats, you'd like an allowlist regexp?

**Comment by b1twise** [comment]
Yes

**Comment by teststaybaka** [comment]
Thanks for your request. Unfortunately I have decided not to add this feature. The filtering feature itself isn't core to this Chrome extension and I don't think it make sense to extend it further. You might want to look for some other Chrome extensions whose features focus on filtering comments.
