### ISSUE TITLE
点击登录但是没有反应

### ISSUE THREAD

**Issue by Firesuiry** [teststaybaka/danmage#2]
点击登录但是没有反应，不会跳出登录页面。。。

**Comment by teststaybaka** [comment]
你看看你的chrome有没有禁止弹窗

**Comment by Firesuiry** [comment]
没有看到那种拦截了一个弹出窗口的提示呢。

**Comment by Firesuiry** [comment]
![image](https://github.com/teststaybaka/danmage/assets/30189673/441a8dbf-6801-4ec5-b980-53e734201340)
我在官网上登录了，但是插件里显示还是没登录

**Comment by teststaybaka** [comment]
网站上和扩展上是分开的。那在youtube上，右键inspect网页，然后登录，看看有没有什么错误。

**Comment by Firesuiry** [comment]
![image](https://github.com/teststaybaka/danmage/assets/30189673/14667f27-c740-4445-bb48-3a3ee3d5139f)
控制台没有新的日志啥的，我点登录没反应

**Comment by Firesuiry** [comment]
用的版本是Microsoft Edge
版本 120.0.2210.144 (正式版本) (64 位)

**Comment by Firesuiry** [comment]
chrome测试正常了，就是Edge不行

**Comment by teststaybaka** [comment]
额，edge还能装chrome extension？那难怪了。用的是chrome的API，大概率有些API被edge改了。
