### ISSUE TITLE
边放视频边打弹幕的时候，按空格导致视频暂停

### ISSUE THREAD

**Issue by Firesuiry** [teststaybaka/danmage#3]
边放视频边打弹幕的时候，按空格导致视频暂停
有点难受。。

**Comment by teststaybaka** [comment]
hmmm，我以前测试过是没问题的。我今天测了一下确实有这个问题。

我[这里](https://github.com/teststaybaka/danmage/blob/69b153c3fd7c95c56dac2ad1d2fe549b20cc75a1/frontend/chrome_extension/content_script/common/custom_text_input_controller.ts#L39) 确实是用了`event.stopPropagation()`， 然后我又加上了所有能加的`event.stopImmediatePropagation()`，`event.preventDefault()`，字都打不出来了，还是能暂停...

唉，youtube还是霸道啊...抱歉，真修不好这个...

**Comment by Firesuiry** [comment]
> hmmm，我以前测试过是没问题的。我今天测了一下确实有这个问题。
> 
> 我[这里](https://github.com/teststaybaka/danmage/blob/69b153c3fd7c95c56dac2ad1d2fe549b20cc75a1/frontend/chrome_extension/content_script/common/custom_text_input_controller.ts#L39) 确实是用了`event.stopPropagation()`， 然后我又加上了所有能加的`event.stopImmediatePropagation()`，`event.preventDefault()`，字都打不出来了，还是能暂停...
> 
> 唉，youtube还是霸道啊...抱歉，真修不好这个...

也没办法~~话说有个小建议，要是能发一条弹幕就自动发一个评论，写上又XX弹幕助手发送，估计人会多不少~~

**Comment by teststaybaka** [comment]
大概看了一下，这个不太好做，因为youtube API有quota限制。不过感谢建议！

**Comment by teststaybaka** [comment]
发现是keyup event导致暂停。等3.6.5版本发布。
