### ISSUE TITLE
firefox support

### ISSUE THREAD

**Issue by Littleweisheit** [teststaybaka/danmage#5]

**Comment by teststaybaka** [comment]
hmmm...not very motivated...

**Comment by teststaybaka** [comment]
Your wish has been granted! Get it here: https://addons.mozilla.org/en-US/firefox/addon/danmage/

Let me know if you found any issue. Thanks!

**Comment by teststaybaka** [comment]
Closed.

**Comment by iamalexblue** [comment]
太棒了，好多插件都只做 Chrome Web Store 版本的，特意来感谢还为 Firefox 开发插件的开发者！！！
